aggregator/database/database.go, aggregator/database/database_test.go, aggregator/database/mocks/database.go, aggregator/rest_server.go, aggregator/rest_server_test.go, aggregator/types/types.go, core/types/types.go
This PR adds support for fetching checkpoint messages (i.e. getting messages and aggregations filtering by timestamp) and adds a `/checkpoint/messages` `GET` route that fetches this data and responds to it.
This is also ready, but on draft until #48 is merged - then it will be updated. Anyway, feel free to review @taco-paco
=> Add checkpoint message fetching

aggregator/aggregator.go, aggregator/rollup_broadcaster.go, config-files/aggregator-docker-compose.yaml, config-files/aggregator.yaml, operator/attestor/attestor.go, operator/consumer/consumer.go, operator/consumer/queues_listener.go, operator/rpc_client.go, tests/integration/integration_test.go
Issues:
1. Prior messages that failed to be resend were dropped, hence never got to aggregator.
2. Port 5000 is occupied on Mac by Airplay
Introduced:
Rpc client now has a queue of unsent messages
1. All messages that failed to be send make it into queue.
2. On every new send we try to resend existing messages
3. The messages that failed to be send are remained in the queue
4. Try to send current message. In case failed see 1.
There's also a timer that occasionally triggers resend
=> Fix integration tests on Mac

operator/rpc_client.go
As pointed out by `go-staticcheck`, this type switch could be trivially simplified.
=> Refactor unnecessary type assertions on type switch

Cargo.lock, indexer/Cargo.toml, indexer/Dockerfile, relayer/cmd/Dockerfile, rust-toolchain.toml
The current nearcore was considerably outdated, and it could not parse the config fields anymore.
Used the same ref as https://github.com/near/near-lake-indexer/.
=> Bump nearcore version

operator/operator.go, setup/operator/config/operator.yaml
Now an operator can simply leave `register_operator_on_startup` as `true` by default - if it's not registered yet, it'll be registered, otherwise the registration will be simply skipped. This makes it unnecessary to use the operator plugin CLI for registering.
=> Improve AVS registering flow

operator/rpc_client.go
It seems excessive to try resending messages on every send, before the actual message is sent. If we know the original message send did not work, it doesn't make sense to retry for the enqueued ones.
=> Resend from queue on message send only if successful

indexer/src/main.rs
Indexing from interruption was basically making it so it indexes *everything* from the latest interruption, effectively making it so the indexer would be behind the block rate for quite some time before actually reaching the current block.
This would be interesting if we made use of this capability somehow, but considering timeouts from MQ and message aggregation, if the indexer is ever stopped, the operator would already be inactive enough for this to be a fault and timeouts would be easily reached (startup takes quite a while).
In the end, keeping it like that only makes it so the operator doesn't realize there's a submission for current messages and has older messages to sign that he's already inactive for, which is what was happening in the testing environment.
=> Start indexing from latest block synced

operator/attestor/notifier.go
We were basically reaching a 'deadlock'-like state because the queue was full and as such the MQ listener was not being able to listen anymore.
=> Increase block data buffer on notifier

core/chainio/avs_writer.go
Currently, specifically the RespondToCheckpointTask submissions are reverting because of OOG. This is curious because it's the only transaction in which it happens, but it's the case. Still, for basically any call it seems like `go-ethereum` doesn't add a considerable amount of extra gas to avoid issues, most transactions are really really close. For calls that are afected by the state somehow, it would be good to follow a similar approach. Double-checked replaying it through a fork and it works with a tiny bit more gas.
=> Add additional gas to RespondToCheckpointTask transaction

operator/attestor/attestor.go
The prometheus metrics are not supposed to be re-registered, as was currently happening on reconnects. This leads to a panic: `panic: duplicate metrics collector registration attempted`.
=> Fix collectors being re-registered on reconnect

relayer/relayer.go
After quite some execution time, there was this error: `NEAR DA client handler error: [An error happened during transaction execution: Expired]`. Transactions expiring are also a possibility, so including them in the resubmission logic.
=> Also resubmit blocks to NEAR DA on expired transaction

operator/attestor/notifier.go, relayer/relayer.go
We're probably overestimating NEAR's throughput here. Even with these changes, transactions are still expiring (after 3 retries) frequently. Still going to try increasing the usual interval a bit more and also retries to check this out, as it's unclear whether this is affected by our transaction rate or not. Maybe we need to push this through another RPC besides the default one?
Even on a retry it's still nowhere near 100, but I also increased notifier's channel queue size for some additional safety - we can probably increase it quite a bit more still.
=> Increase relayer intervals

aggregator/aggregator.go, aggregator/aggregator_test.go, aggregator/rollup_broadcaster.go
In all of these cases, the transactions can take long to be included and this can delay the loop.
=> Send transactions through goroutines

setup/aggregator/docker-compose.yml, setup/operator/docker-compose.yml, setup/relayer/docker-compose.yml
Just adds logrotate to the main containers. These are pretty big limits, but we are logging a lot (and it's good we do it - though I think I can remove some of the mq logs on operator, it's a bit much), but this will make sure it will not blow up anyone's storage.
=> Add logrotate to setup docker composes

aggregator/aggregator.go, core/chainio/avs_writer.go, tests/integration/integration_test.go
Because of how the EL BLS aggregation contracts work, you can't respond to a task in the same block it was created.
=> Only respond to task in the next block

aggregator/aggregator.go, aggregator/rpc_server.go, operator/mocks/rpc_client.go, operator/operator.go, operator/rpc_client.go
This introduces a check for the aggregator's `RegistryCoordinator` address in the operator as an additional layer to detect misconfigurations. If they don't match, it means the operator is misconfigured in either the contract address or the aggregator socket. Still not totally sure if this should be a `Fatal` or not.
=> Check registry coordinator addresses match on operator startup

aggregator/rollup_broadcaster.go
This does not really have any impact as it doesn't actually re-initialize, since the simulated calls would revert anyway.
=> Avoid re-initializing operator set

docker-compose.yml
Solves #163 by using `0.0.0.0` over `localhost` in healthchecks.
=> Prefer `0.0.0.0` over `localhost`

core/safeclient/client.go
Just noticed something that passed us by during #154 - `handleReinitEvent` has a `defer c.wg.Done()` even though the wait group is not incremented when it's called. It was probably a byproduct of a refactor, as now it spawns it's own task. In this case, it makes sense to just remove it.
=> Fix double decrement on SafeEthClient wg

aggregator/metrics.go
Quick fix - rollup IDs being formatted as hex in aggregator metric labels.
=> Format rollupId as decimal in aggregator metrics

aggregator/metrics.go, aggregator/rpc_server.go, grafana/provisioning/dashboards/AVSs/aggregator.json, operator/operator.go, operator/rpc_client.go
Adds a simple metric to track operator initializations in aggregator. The idea here is not that we strictly need to know that operator X has initialized, but at least have some kind of ping so we can detect crashes if they happen.
=> Add operator initialization metric to aggregator

aggregator/rollup_broadcaster.go, operator/attestor/attestor.go, operator/avs_manager.go, relayer/relayer.go
Now that all our subscriptions are made through a `SafeEthClient`, the only situations in which there is a subscription error are either when the client is being closed or the context is ended - both cases mean deliberately exiting (and in our case program exit). So, we can just standardize unsubbing and (if receiver) closing the channel whenever there is an error.
Ideally none of these steps would be necessary and are functionally changing anything if we assume the unsubbing has already happened and the channel can be closed automatically on GC, but if there ever is some extra reason at least we're not leaking anything.
=> Standardize subscription error handling

core/safeclient/client.go
Was reviewing and re-testing and noticed the proxy channel is not used on the first `SubscribeNewHead` call. This is not too problematic as a new sub will be made right after and everything will work as intended, but should be fixed anyway.
=> Fix first header subscription using non-proxy channel

.github/workflows/integration-tests.yml, Makefile, config-files/plugin.anvil.yaml, plugin/cmd/main.go, plugin/cmd/operator_plugin.go, tests/integration/integration_test.go, tests/integration/registration_test.go, tests/integration/utils/containers.go
Something that passed us by on #171 - the plugin receivers considered the context would be part of the struct, but it wasn't being assigned on the constructor. For now, I removed the interface, as we're not having much use for it, and made it so the receivers get the context. Saving contexts is a bit weird, so I think this is for the best, and we can get a common interface later.
I also added an integration test for opt-in/opt-out operations.
It's important to merge this quickly so we have registering working.
=> Fix plugin registration and add registration int test

core/safeclient/client.go
We were stopping the header ticker once a successful resub happened, but we actually *should* leave it running because sometimes providers just stop sending blocks without an underlying error. With this, we do try to resub if there are no blocks received in that time window.
=> Remove header ticker stopping on SafeEthClient

aggregator/aggregator.go, aggregator/message_blsagg.go, aggregator/rpc_server.go, cli/actions/register_operator_with_avs.go, core/chainio/avs_subscriber.go, core/chainio/avs_writer.go, operator/attestor/attestor.go, operator/avs_manager.go, operator/operator.go, relayer/cmd/main.go, relayer/relayer.go
Resolves #179. Replaces all occurrences of formatting logging (`logger.<LEVEL>f`) for tags.
Some log statements where using formatting variants despite not leveraging formatting at all.
=> Prefer tags for logging

core/safeclient/client.go
This PR makes two small improvements on resubscriptions:
1. If the subscription didn't fail but the log filtering did, the underlying subscription is still changed
2. The resub ticker is reset no matter what, as in the end we're rate limiting resubs
=> Improve resubscription error handling

core/safeclient/client.go
...And one more small fix. The block chunking in some cases could lead to a larger by one block chunk. We are in need of some better testing on this client.
=> Fix non-exact block chunking

core/safeclient/client.go, core/safeclient/client_test.go
Fixes #199 by using `sync.Once` to avoid double-closing a channel
=> Fix `SafeEthClient` concurrent close

.github/workflows/deny-checks.yml
Closes #205 by updating and pinning the `cargo-deny` and `taiki-e/install-action` tools
=> Update `cargo-deny` versions

contracts/evm/test/utils/BLSUtilsFFI.sol
Since `bls-utils` is part of the global workspace, it is built into the `near-sffl/target/debug` directory. 
How to run test:
```shell
cd contracts/evm
forge test --ffi
```
=> Fix path to bls-utils

core/safeclient/client_test.go
Fixes #207 by adding locks when needed and proper channel flushing. Issues were detected by using the `-race` flag. Only test code was changed.
=> Fix flaky `SafeEthClient` tests

aggregator/database/database.go
We were having an issue on DB management: whenever the operators were making a checkpoint, they were calling `GetAggregatedCheckpointMessages`, which triggered a `SELECT` on the DB. Since we are continuously writing to the DB as well, if a write happened to be happening at the same time, the DB would be locked, as it's SQLite - not supposed to be concurrent.
An immediate fix to this is simply limiting the connections, as effectively we are not using more than one at once.
=> Limit max DB connections to 1

aggregator/database/database.go, aggregator/database/database_test.go, aggregator/rest_server.go, aggregator/rest_server_test.go
Partially solves https://github.com/NethermindEth/near-sffl/issues/239 by introducing additional bounds checks to the checkpoint messages fetching. It also adds additional tests for parameter deserializing.
Ensures that ranges `from - to` are valid, that is `from < to` is always satisfied.
Certain queries that would previously return an empty result set now return an error message indicating that the range provided is invalid.
There is quite a complicated issue with the storage of `BlockNumber` and `Timestamp` as defined here:
https://github.com/NethermindEth/near-sffl/blob/18544a6716cb6fe0cb91f928ba1f476cc7bcaa5f/core/types/fields.go#L14-L15
> I'm assuming that this timestamp is representing a Unix timestamp
These types are used in `StateRootUpdateMessage` …
=> Server parameter validation

.golangci.yaml, Makefile, aggregator/database/database.go, core/config/config.go, operator/avs_manager.go, operator/rpc_client.go, tests/integration/utils/containers.go
Currently no static analysis tools are being used as part of our build process (either local or CI).
As part of #215, we add [golangci-lint](https://golangci-lint.run) as an additional dependency to lint Go files. The linter can be run using `make lint`.
This is not a breaking change since it adds a new Make target without affecting existing ones. Those who want to use the linter will need to add them to their dev enviroments
This PR also includes some fixes based on the linting results, mostly involving proper error handling (some errors were being ignored).
In the near future we want to:
- Address all current linting issues (fix or ignore accordingly)
- Enable linting for tests files
- Enable linting in CI as an additional check
=> Add Golang linter

aggregator/aggregator.go, aggregator/cmd/main.go, aggregator/rpc_server/server.go, tests/integration/integration_test.go
Currently, the Aggregator constructs a prometheus registry rather than accepting one as a parameter introducing some friction when trying to use the same registry in the RPC/REST servers.
We lift the construction of the registry to `main` and pass it as a parameter to whatever requires it.
No breaking changes since this is merely a refactor.
There is a bit of an implicit assumption that if `config.EnableMetrics == true` then the registry provided as parameter is not `nil`.
=> Inject metrics registry as parameter

aggregator/message_blsagg.go, aggregator/rpc_server/server.go, operator/rpc_client.go
Currently, when logging messages that contain a `bls.Signature` we're logging a pointer address rather than its contents.
Whenever we log these messages we log their value rather that their representation
This change should not introduce any breaking changes.
The original code used `fmt.Sprintf("%#v", ...)` in the log calls which did not dereference the pointers. This behavior is present since #12 but there is no clear indication on why it was done that way.
=> Include signature in message receiving logs

docs/docs/deployments.md, docs/docs/operator/registration.md, docs/docs/operator/setup.md, docs/docusaurus.config.js
The current docs (https://nffl.nethermind.io) still show `NEAR SFFL` in the page title and navbar.
The title and navbar show `NFFL` rather than `SFFL` (fixes https://github.com/NethermindEth/near-sffl/pull/255#issuecomment-2200686227)
There should be no breaking changes.
We missed this on #255
=> Fix SFFL title in docs

docker-compose.yml
NEAR DA data was not being cleared on a docker compose test env reset. The usual fix for this would be resetting the volumes whenever resetting - `docker compose down -v` or such. Still, this may pass unnoticed and cause some confusion.
A related PR is #267.
The above issue is prevented by clearing the relevant data on the `indexer_setup` service. So, when re-upping it should be clean even if the volumes were not reset.
None
=> Clear NEAR DA data on docker compose test env reset

operator/attestor/notifier_test.go, operator/consumer/consumer.go, operator/consumer/queues_listener.go, operator/operator_test.go
In some cases, geth's `types.Block` are copied - mostly because of copying our `BlockData` instances. This is not being problematic in any sense since these locks aren't being used, but it's a small fix anyway.
`BlockData` now includes a `types.Block` as a pointer, which is even more ideal considering how much data that struct holds. Thus, no copies even when copying `BlockData`, which should still be okay.
Not a breaking change.
=> Fix block lock copying

indexer/Dockerfile
The current indexer container healthcheck is not entirely reliable - very rarely the container is marked as healthy before actually being synced. It also does an unnecessary loop for checking the node state.
Related to #242.
Now the healthcheck also tries and fetches the current block, checking it's at most 10s old, before checking the node syncing state. It's also does not loop anymore.
None
=> Refactor indexer healthcheck for reliability

indexer/Cargo.toml, indexer/Dockerfile, rust-toolchain.toml
There should be a new protocol version going live next week through v2.1.0-rc.1.
Updates Rust to 1.79 and the nearcore refs to the 2.1.0-rc.1 reference.
No a breaking changes.
=> Update nearcore to v2.1.0-rc.1

static/avs_metadata.json
NFFL was described as "NEAR Fast Finality Layer" and the twitter URL was NEAR's.
NFFL is now described as "Nuffle Fast Finality Layer" and the twitter URL is now Nuffle Lab's.
None.
=> Update AVS metadata with Nuffle fields

relayer/metrics.go, relayer/relayer.go
Sometimes the NEAR DA client throws timeout errors on a relayer submission. The relayer did consider expiration errors, not timeouts.
The relayer now retries the submission on a timeout.
None.
=> Add retry to Near DA timeout errors on relayer

aggregator/aggregator.go, aggregator/blsagg/message_blsagg.go
With the latest change on #282, checkpoint aggregations are submitted as soon as they're ready.
This PR makes is so the aggregations are only submitted when the aggregation process is finished. This should potentially save us some gas, since even if quorum is reached it waits a bit and aggregates more signatures, which decreases the verification cost.
None.
=> Submit checkpoint aggregation on finished aggregation process

aggregator/aggregator.go, aggregator/aggregator_test.go, aggregator/database/database.go, aggregator/database/database_test.go, aggregator/database/mocks/database.go
We are keeping intermediate aggregations through GORM's Replace leaving them as orphans instead of deleting them.
This PR introduces some changes to make it so aggregations are deleted when being replaced on incremental aggregation.
None.
=> Delete intermediate aggregations on DB replace

aggregator/blsagg/message_blsagg.go
After threshold was reached, `MessageBlsAggregationService` also posted responses even though the message content differed for the same key.
With this PR, after the threshold was reached, which is assumed to be a majority (and enforced in the code), non-majority message signatures are ignored in the aggregation.
None.
=> Ignore mismatching digests after threshold reached

Cargo.lock, indexer/Cargo.toml
Nearcore should have a new protocol version based on v2.2.0-rc.1, while the current indexer version is based on the previous version.
This updates the nearcore dependency version to v2.2.0-rc.1.
Breaking change for the indexer.
=> Update nearcore to v2.2.0-rc.1

aggregator/blsagg/message_blsagg.go, core/types/messages/aggregation.go
`StandardizeMessageBlsAggregation` is not always sorting all non-signer-related slices based on the non-signer pubkey hash. The reason for that is the key slice was being used in the `sort.Slice` `less` to sort another slice, while it was not being sorted together.
The method was removed, as it was not needed, and the ordering was guaranteed when building the object. Some small updates were also done in `MessageBlsAggregationService` to change the approach for getting non-signer pubkeys - it's now simpler and it's not necessary to assume any map behavior.
None.
=> Fix pubkey sorting on aggregations

Cargo.lock, indexer/Cargo.toml
We're using nearcore 2.2.0-rc.1 in the indexer. NEAR issued a [new release](https://github.com/near/nearcore/releases/tag/2.2.0-rc.2) with `CODE_RED`, so we should transition to it as soon as possible.
This updates the nearcore dependency to 2.2.0-rc.2
None.
=> Update nearcore to 2.2.0-rc.2

setup/aggregator/docker-compose.yml, setup/relayer/docker-compose.yml
Currently aggregator and relayer setups instantiate Grafana + Prometheus by default.
This makes it so it's necessary to set the `monitoring` profile to instantiate those, so it's possible to toggle that by including the profile or not.
None.
=> Allow toggling monitoring in aggregator and relayer setups

Makefile, tests/anvil/deploy-rollup-avs-save-anvil-state.sh
We were already generating the rollup contracts anvil state manually for testing, but we didn't have a script for it.
This adds a script similar to the AVS contracts one.
None.
=> Add rollup contracts anvil state generator script

Cargo.lock, indexer/Cargo.toml
nearcore is set to `2.2.0-rc.2`.
nearcore is now set to `2.2.1-rc.1`.
None.
=> Update nearcore to 2.2.1-rc.1

setup/operator/scripts/sync.sh
We redirected the user to the documentation for NEAR nodes syncing. It's simpler if we have a syncing script, since sometimes operators need to re-sync.
This adds a syncing script that copies the snapshot as instructed in the documentation. 
None.
=> Add snapshot syncing script

Cargo.lock, indexer/Cargo.toml, indexer/Dockerfile, indexer/src/configs.rs, rust-toolchain.toml
Nearcore is currently in the previous version, and there is a new protocol update.
Nearcore is now set to 2.3.0-rc.1.
The new protocol version will be enforced by NEAR soon, even though the update itself isn't breaking.
=> Update nearcore to 2.3.0-rc.1
